import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "../globals.css";
import ThemeProvider from "@/context/ThemeProvider";
import DesktopHomeNavbar from "@/components/navigation/homeNavbar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${publicSans.className} antialiased`}>
        <ThemeProvider>
          <DesktopHomeNavbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
