import type { Metadata } from "next";
import "../globals.css";
import DesktopHomeNavbar from "@/components/navigation/homeNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <DesktopHomeNavbar />
      {children}
    </div>
  );
}
