import type { Metadata } from "next";
import "../globals.css";
import DesktopHomeNavbar from "@/components/navigation/homeNavbar";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="w-[100%] h-[100vh] fixed top-0 left-0 z-[-1]">
        <Image
          src={"/bg.jpg"}
          fill
          alt="background image"
          className="object-cover"
        />
      </div>
      <DesktopHomeNavbar />
      {children}
    </div>
  );
}
